### ISSUE TITLE
XML tools written in Rust.

### ISSUE THREAD

**Issue by ghost** [acdh-oeaw/voice-xml-utilities-api#1]
I am a student at the university of Vienna myself and created "ULing" for use in a seminar where we are building our own corpus.
Could ULing, my suite of tools for conducting my linguistic research be useful to VOICE? Here's the link: https://github.com/angedollface/uling

**Comment by simar0at** [comment]
The data processing for this project is finished. If you like however I can send you the data in various formats as a ZIP archive so you can try yourself what your tools can do with the data.
The data is in TEI/XML. Other formats are generated from those files.

**Comment by ghost** [comment]
@simar0at Hi! :heart: Sorry for the late reply!!! I was so busy, it was unreal. Following thoughts about my suggestion and your response:

- I tested the "ULing" tools and there are several issues with them. They mainly derive (no pun intended!) from the `serde-xml` and `serde-derive` crates. When I have more time, I wanted to rewrite/overhaul them anyway. So perhaps I could test them then with the data you suggested.

- Since I'm a passionate Rustacean and also know a whole bunch of other languages  (Python, Dart, SASS, Ruby, Zig, Javascript, Typescript, etc.) and I think maybe I could use those skills for VOICE and other things that may be relevant and useful for the ACDH, I was wondering if it would be possible to do the things you suggested and other things as an employee of the ACDH? I'm gonna finish my bachelor at Uni Wien in 4-5 weeks anyway. (I would be more than happy to send you or whoever is responsible any relevant documents.)

I'm curious what you think! :see_no_evil:

**Comment by ghost** [comment]
I should also add that because I updated some libraries for a bigger project ([Mandy](https://github.com/angeldollface/mandy) - a static-site generator) and implemented better error-handling in these libraries and discontinued some other libraries that the ULing suite depends on, some of the tools in the ULing suite may not build properly. I haven't had the time to update everything yet and implement some of the changes that the new libraries require in ULing itself.

**Comment by simar0at** [comment]
Sorry, I completely missed your reply last year. You can contact [us](https://www.oeaw.ac.at/acdh/) if you consider contract work or we may have open positions.
But after such a long time I hope you already got a good job.
Thanks anyway for giving thsi sime thought!

**Comment by ghost** [comment]
Hi @simar0at can we talk somewhere privately? There are certain things I would like to answer that I cannot say here. (Only positive things, don't worry.)
